/**************************************************************************
 Program:  Rcasd_text2type_fmt.sas
 Library:  DHCD
 Project:  Urban-Greater DC
 Author:   P. Tatian
 Created:  12/03/22
 Version:  SAS 9.4
 Environment:  Local Windows session (desktop)
 GitHub issue:  
 
 Description:  Autocall macro to create $rcasd_text2type. format for 
               recoding RCASD notice descriptions to type codes. 
               
               See Prog\RCASD\Make_formats_rcasd.sas for list of type codes.

 Modifications:
**************************************************************************/

/** Macro Rcasd_text2type_fmt - Start Definition **/

%macro Rcasd_text2type_fmt(  );

  proc format;

    value $rcasd_text2type 
      "CONDOMINIUMREGISTRATIONAPPLICATION",
      "CONDOMINIUMREGISTRATIONAPPLICATIONS",
      'CONDOMINIUMREGISTRATIONAPPLICATION(AMENDED&RESTATED)',
      "CONDOMINIUMREGISTRATIONAPPLICATIONCORRECTIONS",
      'CONDOMINIUMREGISTRATIONAPPLICATIONS&PUBLICOFFERINGSTATEMENTS',
      'APPLICATIONFORCONDOMINIUMREGISTRATION',
      "CONDOMINIUMREGISTRATIONS"= "101"
      
      "NOT-A-HOUSINGACCOMMODATIONEXEMPTIONAPPLICATIONS",
      "NOTAHOUSINGACCOMODATIONAPPLICATION",
      "NOTAHOUSINGACCOMODATION",
      "NOTAHOUSINGACCOMMODATIONAPPLICATIONS",
      "NOTAHOUSINGACCOMMODATIONEXEMPTIONAPPLICATION",
      "NOTAHOUSINGACCOMMODATIONEXEMPTION",
      "NOTAHOUSINGACCOMMODATION",
      "NOTAHOUSINGACCOMMODATIONAPPLICATION",
      "APPLICATIONFORNOTAHOUSINGACCOMODATION",
      "NOT-A-HOUSINGACCOMMODATIONEXEMPTIONAPPLICATION(S)",
      "NOT-A-HOUSINGAPPLICATIONS" = "102"
      
      "VACANCYEXEMPTIONAPPLICATIONS",
      "VACANCYEXEMPTIONAPPLICATION", 
      "VACANCYEXEMPTION",
      "VACANCYEXEMPTIONCERTIFICATIONAPPLICATION",
      "VE",
      "VEAPPLICATION",
      "VACANCYAPPLICATIONS-NOTSCHEDULEDINSYSTEM",
      "VACANCYAPPLICATION",
      "VACANCYEXEMPTIONSAPPLICATION",
      "APPLICATIONFORVACANCYEXEMPTION",
      "VACANCYEXEMPTIONAPPLICATION(S)" = "103"
      
      "LOWINCOMEEQUITYSHARECOOPERATIVECONVERSIONAPPLICATIONS","LIMITEDEQUITYSHARECOOPERATIVECONVERSIONAPPLICATION" = "104"
      
      "TENANTELECTIONAPPLICATIONS",
      "TENANTELECTIONAPPLICATION",
      "TENANTELECTIONREQUEST",
      "TENANTELECTIONREQUESTSFILED",
      "TENANTELECTIONINFORMATION",
      "TENANTELECTION",
      "TENANTELECTIONAPPLICATION(S)" = "105"
      
      "HOUSINGASSISTANCEPAYMENTAPPLICATIONS",
      "HOUSINGASSISTANCEPAYMENTAPPLICATION",
      "HOUSINGASSISTANCEPAYMENTAPPLICATION(RECERTIFICATION#2)",
      "HOUSINGASSISTANCEPAYMENT" = "106"
      
      "PROPERTYTAXABATEMENTAPPLICATIONS", 
      "PROPERTYTAXABATEMENTAPPLICATION", 
      "TAXABATEMENTREQUEST", 
      "TAXABATEMENTAPPLICATIONS" = "107"

      "WARRANTYCLAIMCORRESPONDENCE" = "108"
      
      "CONVERSIONELECTIONREQUEST/INFORMATION",
      "CONVERSIONELECTIONINFORMATION" = "109"
      
      "CONDOMINIUMEXEMPTIONREQUEST(VACANT)",
      "CONVERSIONEXEMPTIONS(VACANT)"
      "CONVERSIONEXEMPTIONREQUEST(VACANT)" = "110"
      
      "EXEMPTIONFROMTENANTELECTIONREQUEST(CONVERSIONFROMCOOPTOCONDO)" = "111"
      
      "ELECTIONCORRESPONDENCE",
      "TENANTELECTIONMATERIALS",
      "ELECTIONCORRESPONDENCEANDMATERIALS" = "112"
      
      "CONVERSIONELECTION" = "114"
      
      "TENANTCONVERSIONELECTIONAPPLICATIONS" = "115"
      
      "CONVERSIONELECTIONREQUEST(SUBMITTEDBYOWNERTOTENANTS)" = "117"
      
      "CONDOMINIUMCONVERSIONCOMPLAINT" = "118"
      
      "CONDOMINIUMEXEMPTIONREQUEST(NON-HOUSING)" = "120"
      
      'CONDOMINIUMREGISTRATIONAPPLICATIONCORRECTIONS-SFDNOTICEOFSOLICITATIONOFOFFER&NOTICEOFINTENTTOSELL' = "121"
      
      "CONVERSIONEXEMPTIONREQUEST", "CONVERSIONEXEMPTIONS", "CONVERSIONEXEMPTIONAPPLICATION",
      "CONDOMINIUMCONVERSIONEXEMPTIONAPPLICATION" = "125"
      
      "CONVERSIONEXEMPTIONINFORMATION" = "126"
      
      "ELECTIONREQUESTFORCONDOCONVERSION" = "127"
      
      "ELECTIONREQUEST", 'ELECTIONREQUEST&TENANTFORMS' = "130"
      
      "CONVERSION-CONDOMINIUMREGISTRATIONAPPLICATION",
      'CONVERSION-CONDOMINIUMREGISTRATIONAPPLICATIONS' = "140"
      
      "CONVERSION-NOTAHOUSINGACCOMMODATIONEXEMPTIONAPPLICATION" = "141"
      
      "CONVERSION-VACANCYEXEMPTIONAPPLICATION" = "142"
      
      "CONVERSION-PROPERTYTAXABATEMENTAPPLICATION" = "143"
      
      "CONVERSION-TENANTELECTIONCORRESPONDENCE-5+UNITSRIGHTOFFIRSTREFUSAL" = "144"
      
      'CONVERSION-NOTAHOUSINGACCOMMODATIONEXEMPTIONAPPLICATION-SFDNOTICEOFSOLICITATIONOFOFFER&NOTICEOFINTENTTOSELL' = "145"
      
      "CONVERSION-TENANTELECTIONAPPLICATION" = "146"
      
      'CONVERSION-WARRANTYSECURITYBOND-SFDNOTICEOFSOLICITATIONOFOFFER&NOTICEOFINTENTTOSELL' = "147"
      
      'CONVERSION-WARRANTYCLAIM-SFDNOTICEOFSOLICITATIONOFOFFER&NOTICEOFINTENTTOSELL' = "148"
      
      'CONVERSION-WARRANTYSECURITYLETTEROFCREDIT-SFDNOTICEOFSOLICITATIONOFOFFER&NOTICEOFINTENTTOSELL' = "149"
      
      'CONVERSION-LIMITEDEQUITYSHARECOOPERATIVECONVERSIONAPPLICATION',
      'LIMITEDEQUITYSHARECOOPERATIVECONVERSIONAPPLICATION-SFDNOTICEOFSOLICITATIONOFOFFER&NOTICEOFINTENTTOSELL' = "150"
      
      'CONVERSION-NOTAHOUSINGACCOMMODATIONEXEMPTIONAPPLICATION-LETTEROFINTEREST(TOPA)' = "151"
      
      'CONVERSION-SFDNOTICEOFSOLICITATIONOFOFFER&NOTICEOFINTENTTOSELL',
      'CONVERSION-CONDOMINIUMREGISTRATIONAPPLICATION-SFDNOTICEOFSOLICITATIONOFOFFER&NOTICEOFINTENTTOSELL' = "152"
      
      'CONVERSION-WARRANTYCLAIMCORRESPONDENCE-SFDNOTICEOFSOLICITATIONOFOFFER&NOTICEOFINTENTTOSELL' = "153"
      
      "LETTEROFCREDITAMENDMENT-LETTEROFINTEREST(TOPA)" = "160"
      
      'NOTAHOUSINGACCOMMODATIONEXEMPTIONAPPLICATION-SFDNOTICEOFSOLICITATIONOFOFFER&NOTICEOFINTENTTOSELL' = "161"
      
      "NOTAHOUSINGACCOMMODATIONEXEMPTIONAPPLICATION-RAZEPERMITAPPLICATION" = "162"

      "NOTICEOFTRANSFER", 
      "NOTICESOFTRANSFER", 
      "NOTICEOFTRANSFER/CORRESPONDENCE", 
      "NOTICEOFTRANSFERCORRESPONDENCE",
      "NOTICEOFTRANSFER-AFFIDAVITOFMAILING" = "201"
      
      "OTHERFILINGS" = "202"
      
      "NOTICESOFFORECLOSURE",
      "FORECLOSURENOTICE",
      "FORECLOSURENOTICES",
      "NOTICEOFFORECLOSURE" = "203"
      
      "DCOPPORTUNITYTOPURCHASEACTDOPANOTICES",
      "DCOPPORTUNITYTOPURCHASEACTNOTICES",
      "DCOPPORTUNITYTOPURCHASENOTICE",
      "DCOPPORTUNITYTOPURCHASEACT(DOPA)NOTICES",
      "DOPANOTICE",
      "DOPANOTICE(DISTRICTOPPORTUNITYTOPURCHASE)",
      "DOPANOTICE(5+)" = "204"
      
      "RAZEPERMITAPPLICATIONS", "RAZEPERMITAPPLICATION", "RAZEPERMITS", "RAZEPERMIT" = "205"
      
      "PETITIONSFORDECLARATORYRELIEF", 
      "PETITIONFORDECLARATORYRELIEF", 
      "PETITIONFORRECONSIDERATION-PETITIONFORDECLARATORYRELIEF" = "206"
      
      "TENANTORGANIZATIONREGISTRATIONAPPLICATION",
      "TENANTORGANIZATIONREGISTRATIONAPPLICATIONS",
      "TENANTORGANIZATIONREGISTRATION",
      "TENANTASSOCIATIONREGISTRATIONFILINGS",
      "TENANTASSOCIATIONREGISTRATIONS",
      "TENANTASSOCIATIONREGISTRATION",
      "TENANTASSOCIATIONREGISTRATION(INRESPONSETOOFFEROFSALE)",
      "TENANTASSOCIATIONREGISTRATIONAPPLICATION" = "207"

      "RIGHTSOFFIRSTREFUSAL",
      "RIGHTOFFIRSTREFUSAL",
      "RIGHTOFFIRSTREFUSALNOTICES(SF,2-4&5+UNITS)",
      "RIGHTOFFIRSTREFUSALNOTICE",
      "RIGHTOFFIRSTREFUSALNOTICES",
      "RIGHTOFFIRSTOFREFUSAL",
      "RIGHTOFFIRSTREFUSALW/CONTRACT",
      'RIGHTOFFIRSTREFUSAL&AFFIDAVITOFDELIVERY',
      "RIGHTOFFIRSTREFUASL" = "211"
      
      "TOPALETTEROFINTEREST",
      "LETTEROFINTERESTTOPA","LETTEROFINTEREST(TOPA)",
      "LETTEROFINTEREST" = "212"
      
      "TOPAASSIGNMENTOFRIGHTS",
      "ASSIGNMENTOFRIGHTTOPA",
      "ASSIGNEMETOFRIGHTTOPA", 
      "ASSIGNMENTOFRIGHTS", 
      "ASSIGNMENTOFRIGHTS(TOPA)",
      "ASSIGNMENTOFRIGHT(TOPA)" = "213"
      
      "TOPACOMPLAINT","TOPACOMPLAINTS", "TOPACOMPLIANT", "COMPLAINT", "COMPLAINT(TOPA)" = "214"
      
      'SFDNOTICEOFSOLICITATIONOFOFFER&NOTICEOFINTENTTOSELL',
      'SINGLEFAMILYDWELLINGNOTICEOFSOLICITATIONOFOFFER&NOTICEOFINTENTTOSELL' = "215"
      
      "SFDLETTERTOLANDLORD",
      "TENANTSNOTICETOLANDLORD",
      "TENANTSLETTERTOLANDLORD" = "216"
      
      "SFDCLAIMOFELDERLYORDISABLEDSTATUS",
      "TENANTSCLAIMOFELDERLY/DISABLEDSTATUS" = "217"
      
      "OFFEROFSALERESPONSE-TENANTS",
      "TENANTRESPONSETOOFFEROFSALENOTICES",
      "TENANTRESPONSETOOFFEROFSALENOTICE" = "218"
      
      "NOTICEOFTRANSFER-EXEMPTIONFROMTOPARIGHTS",
      "NOTICEOFTRANSFER-EXEMPTTRANSACTIONSFROMTOPARIGHTS" = "219"
      
      "2-4UNITSNOTICEOFTRANSFER", "NOTICEOFTRANSFER(2-4)" = "227"
      
      "5+UNITSNOTICEOFTRANSFER", "NOTICEOFTRANSFER(5+MORE)", "NOTICEOFTRANSFER(5+)" = "230"
      
      "TENANTASSOCIATIONREGISTRATION(W/INTENTTOPURCHASE)",
      "TENANTASSOCIATIONREGISTRATIONANDLETTEROFINTERESTTOPURCHASE",
      "TENANTASSOCIATIONREGISTRATION(RESPONSETOOFFEROFSALE)" 
      "TENANTASSOCIATIONREGISTRATION(RESPONSETOOFFEROFSALEBYOWNER)",
      "TENANTASSOCIATIONREGISTRATION-OFS",
      "TENANTASSOCIATIONREGISTRATION(RESPONSETOOFFEROFSALE)",
      "TENANTASSOCIATIONREGISTRATION(RESPONSETOOFFEROFSALEBYOWNER)" = "235"
      
      "TENANTSTATEMENTOFINTERESTTOPURCHASE",
      "TENANTSTATEMENT",
      "STMTOFINTEREST-T/A",
      "STATEMENTOFINTEREST",
      "TENANTSTATEMENTOFINTEREST" = "237"
      
      'RIGHTOFFIRSTREFUSAL&TENANTWAIVEROFRIGHTTOPURCHASE' = "238"
      
      "RIGHTOFFIRSTREFUSAL(SFD)",
      "SFDRIGHTOFFIRSTREFUSAL",
      "RIGHTOFFIRSTREFUSAL(SINGLEFAMILY)",
      "RIGHTOFFIRSTREFUSAL(SF)",
      "RIGHTOFFIRST(SFD)",
      "RIGHTOFFIRSTOFREFUSAL(SFD)",
      "RIGHTOFFIRSTREFURSAL(SFD)",
      "RIGHTOFFIRSTOFREFUSAL(SFD)W/CONTRACT",
      "RIGHTOFFIRSTREFUSAL(SFD)W/OCONTRACT",
      "RIGHTOFFIRSTREFUSAL(SFD)W/CONTRACT",
      "RIGHTOFFIRSTREFUSAL(SFD(",
      "RIGHTOFFIRSTREFUSAL(SFD))",
      "RIGHTOFFIRSTREFUSAL9SFD)",
      "RIGHTOFFIRSTREFUSAL((SFD)",
      "RIGHTOFFIRSTREFUSL(SFD)" = "241"
      
      "2-4UNITSRIGHTOFFIRSTREFUSAL",
      "RIGHTOFFIRSTREFUSAL(2-4)",
      "RIGHTOFFIRSTREFUSAL(2-4UNITS)",
      "RIGHTOFFIRSTREFUSAL2-4",
      "RIGHTOFFIRSTOFREFUSAL(2-4)",
      "RIGHTOFFIRSTREFUSALW/CONTRACT(2-4)",
      "RIGHTOFFIRSTREFUSAL(2-4)W/CONTRACT",
      "RIGHTOFFIRSTREFUSAL2-4)",
      "RIGHTOFFIRSTREFUSAL2-4RENTALUNIT",
      "RIGHTOFFIRSTREFUSAL(2-4)RENTALUNITS",
      "RIGHTOFFIRSTREFUSAL2-4UNIT",
      "RIGHTOFFIRSTREFUSAL2-4RENTALUNITS" = "242"

      "SFDNOTICEOFTRANSFER",
      "NOTICEOFTRANSFER(SFD)" = "243"

      "PETITIONFORRECONSIDERATION" = "244"

      "WARRANTYSECURITYRELEASEREQUEST",
      'WARRANTYSECURITYRELEASEREQUEST-SFDNOTICEOFSOLICITATIONOFOFFER&NOTICEOFINTENTTOSELL' = "245"
      
      "5+UNITSRIGHTOFFIRSTREFUSAL",
      "RIGHTOFFIRSTREFUSAL(5ORMORE)",
      "RIGHTOFFIRSTREFUSAL(5+MORE)",
      "RIGHTOFFIRSTREFUSAL(5+)",
      "RIGHTOFFIRSTREFUSAL(5+MORE)W/CONTRACT",
      "RIGHTOFFIRSTREFUSAL5+RENTALUNITS" = "246"

      "WARRANTYSECURITYLETTEROFCREDIT", 
      "WARRANTYSECURITY?LETTEROFCREDIT"  = "247"
      
      "NOTICEOFTRANSFERCERTIFICATIONREQUEST" = "250"
      
      "NOTICEOFINTENTTOFILEAPETITIONFORRELIEF(NOTICEOFTRANSFER)" = "252"
      
      "PETITIONFORDECLARATORYRELIEFANDREQUEST(T/A)" = "253"
      
      "NOTICEOFINTENTTOCONVERT" = "260"
      
      "NOTICEOFINTENTTOCONVERT(OFFERTOPURCHASECONDOMINIUMUNIT)" = "261"
      
      "NOTICEOFINTENTTOCONVERT(NOTICEAFTERCONVERSION)" = "262"
      
      "CONVERSIONFEE/CORRESPONDENCE" = "265"
      
      "CONVERSIONFEEPAYMENT" = "267"
      
      "CONVERSIONFEEREDUCTIONREQUEST" = "268"
      
      "OFFEROFSALENOTICECORRESPONDENCE",
      "OFFEROFSALECORRESPONDENCE",
      "OTHEROFFEROFSALECORRESPONDENCE",
      "OFFEROFSALEMISCELLANEOUSCORRESPONDENCE" = "270"
      
      "OFFEROFSALE(MISCINFORMATION)",
      "OFFEROFSALE(MISCELLANEOUSINFORMATION)",
      "OFFEROFSALE-MISCDOCUMENTS" = "275"
      
      "CONDOMINIUMCONVERSIONSVACANCYEXEMPTIONINSPECTIONSLISTING" = "280"
      
      "VACANCY/NHAEXEMPTIONAPPLICATIONS" = "282"
      
      "CONVERSIONEXEMPTIONS(VACANT)",
      "CONVERSIONEXEMPTIONREQUEST(VACANT)" = "285"
      
      "COOPERATIVECONVERSIONEXEMPTIONAPPLICATION",
      "COOPERATIVECONVERSIONEXEMPTION" = "290"
      
      "VACANCY/COOPEXEMPTIONAPPLICATION" = "291"
      
      "COOPERATIVECONVERSIONREGISTRATIONAPPLICATION" = "292"
      
      "EXEMPTIONREQUEST",
      "EXEMPTIONREQUESTAPPLICATION",
      "EXEMPTIONAPPLICATIONS" = "295"
      
      "MISCELLANEOUSINFORMATION" = "300"
      
      "TERMINATIONOFCONDOMINIUM" = "310"
      
      "TERMINATIONOFSALESCONTRACT" = "312"
      
      "SALESCONTRACT" = "320"
      
      "DISABILITYSURVEYFORTENANTELECTION" = "330"
      
      "INTENTTOFILEPETITION",
      "NOTICEOFINTENTTOFILEPETITION" = "335"
      
      other = " ";

  run;

%mend Rcasd_text2type_fmt;

/** End Macro Definition **/

