/**************************************************************************
 Program:  Rcasd_text2type_fmt.sas
 Library:  DHCD
 Project:  Urban-Greater DC
 Author:   P. Tatian
 Created:  12/03/22
 Version:  SAS 9.4
 Environment:  Local Windows session (desktop)
 GitHub issue:  
 
 Description:  Autocall macro to create $rcasd_text2type. format for 
               recoding RCASD notice descriptions to type codes. 
               
               See Prog\RCASD\Make_formats_rcasd.sas for list of type codes.

 Modifications:
**************************************************************************/

/** Macro Rcasd_text2type_fmt - Start Definition **/

%macro Rcasd_text2type_fmt(  );

  proc format;

    value $rcasd_text2type 
      "CONDOMINIUMREGISTRATIONAPPLICATION",
      "CONDOMINIUMREGISTRATIONAPPLICATIONS",
      'CONDOMINIUMREGISTRATIONAPPLICATION(AMENDED&RESTATED)',
      "CONDOMINIUMREGISTRATIONAPPLICATIONCORRECTIONS",
      'CONDOMINIUMREGISTRATIONAPPLICATIONS&PUBLICOFFERINGSTATEMENTS',
      'APPLICATIONFORCONDOMINIUMREGISTRATION' = "101"
      
      "NOT-A-HOUSINGACCOMMODATIONEXEMPTIONAPPLICATIONS",
      "NOTAHOUSINGACCOMODATIONAPPLICATION",
      "NOTAHOUSINGACCOMODATION",
      "NOTAHOUSINGACCOMMODATIONAPPLICATIONS",
      "NOTAHOUSINGACCOMMODATIONEXEMPTIONAPPLICATION",
      "NOTAHOUSINGACCOMMODATIONEXEMPTION",
      "NOTAHOUSINGACCOMMODATION",
      "NOTAHOUSINGACCOMMODATIONAPPLICATION",
      "APPLICATIONFORNOTAHOUSINGACCOMODATION" = "102"
      
      "VACANCYEXEMPTIONAPPLICATIONS",
      "VACANCYEXEMPTIONAPPLICATION", 
      "VACANCYEXEMPTION",
      "VACANCYEXEMPTIONCERTIFICATIONAPPLICATION",
      "VE",
      "VEAPPLICATION",
      "VACANCYAPPLICATIONS-NOTSCHEDULEDINSYSTEM",
      "VACANCYAPPLICATION",
      "VACANCYEXEMPTIONSAPPLICATION",
      "APPLICATIONFORVACANCYEXEMPTION" = "103"
      
      "LOWINCOMEEQUITYSHARECOOPERATIVECONVERSIONAPPLICATIONS","LIMITEDEQUITYSHARECOOPERATIVECONVERSIONAPPLICATION" = "104"
      
      "TENANTELECTIONAPPLICATIONS",
      "TENANTELECTIONAPPLICATION",
      "TENANTELECTIONREQUEST",
      "TENANTELECTIONREQUESTSFILED",
      "TENANTELECTIONINFORMATION",
      "TENANTELECTION" = "105"
      
      "HOUSINGASSISTANCEPAYMENTAPPLICATIONS",
      "HOUSINGASSISTANCEPAYMENTAPPLICATION",
      "HOUSINGASSISTANCEPAYMENTAPPLICATION(RECERTIFICATION#2)",
      "HOUSINGASSISTANCEPAYMENT" = "106"
      
      "PROPERTYTAXABATEMENTAPPLICATIONS", "PROPERTYTAXABATEMENTAPPLICATION", "TAXABATEMENTREQUEST" = "107"

      "WARRANTYCLAIMCORRESPONDENCE" = "108"
      
      "CONVERSIONELECTIONREQUEST/INFORMATION",
      "CONVERSIONELECTIONINFORMATION" = "109"
      
      "CONDOMINIUMEXEMPTIONREQUEST(VACANT)",
      "CONVERSIONEXEMPTIONS(VACANT)"
      "CONVERSIONEXEMPTIONREQUEST(VACANT)" = "110"
      
      "EXEMPTIONFROMTENANTELECTIONREQUEST(CONVERSIONFROMCOOPTOCONDO)" = "111"
      
      "ELECTIONCORRESPONDENCE",
      "TENANTELECTIONMATERIALS",
      "ELECTIONCORRESPONDENCEANDMATERIALS" = "112"
      
      "CONVERSIONELECTION" = "114"
      
      "TENANTCONVERSIONELECTIONAPPLICATIONS" = "115"
      
      "CONVERSIONELECTIONREQUEST(SUBMITTEDBYOWNERTOTENANTS)" = "117"
      
      "CONDOMINIUMCONVERSIONCOMPLAINT" = "118"
      
      "CONDOMINIUMEXEMPTIONREQUEST(NON-HOUSING)" = "120"
      
      "CONVERSIONEXEMPTIONREQUEST", "CONVERSIONEXEMPTIONS", "CONVERSIONEXEMPTIONAPPLICATION",
      "CONDOMINIUMCONVERSIONEXEMPTIONAPPLICATION" = "125"
      
      "CONVERSIONEXEMPTIONINFORMATION" = "126"
      
      "ELECTIONREQUESTFORCONDOCONVERSION" = "127"
      
      "ELECTIONREQUEST", 'ELECTIONREQUEST&TENANTFORMS' = "130"
      
      "CONVERSION-CONDOMINIUMREGISTRATIONAPPLICATION" = "140"
      
      "CONVERSION-NOTAHOUSINGACCOMMODATIONEXEMPTIONAPPLICATION" = "141"
      
      "CONVERSION-VACANCYEXEMPTIONAPPLICATION" = "142"
      
      "NOTICEOFTRANSFER", 
      "NOTICESOFTRANSFER", 
      "NOTICEOFTRANSFER/CORRESPONDENCE", 
      "NOTICEOFTRANSFERCORRESPONDENCE",
      "NOTICEOFTRANSFER-AFFIDAVITOFMAILING" = "201"
      
      "OTHERFILINGS" = "202"
      
      "NOTICESOFFORECLOSURE",
      "FORECLOSURENOTICE",
      "FORECLOSURENOTICES",
      "NOTICEOFFORECLOSURE" = "203"
      
      "DCOPPORTUNITYTOPURCHASEACTDOPANOTICES",
      "DCOPPORTUNITYTOPURCHASEACTNOTICES",
      "DCOPPORTUNITYTOPURCHASENOTICE",
      "DCOPPORTUNITYTOPURCHASEACT(DOPA)NOTICES" = "204"
      
      "RAZEPERMITAPPLICATIONS", "RAZEPERMITAPPLICATION", "RAZEPERMITS" = "205"
      
      "PETITIONSFORDECLARATORYRELIEF", "PETITIONFORDECLARATORYRELIEF" = "206"
      
      "TENANTORGANIZATIONREGISTRATIONAPPLICATION",
      "TENANTORGANIZATIONREGISTRATIONAPPLICATIONS",
      "TENANTORGANIZATIONREGISTRATION",
      "TENANTASSOCIATIONREGISTRATIONFILINGS",
      "TENANTASSOCIATIONREGISTRATIONS",
      "TENANTASSOCIATIONREGISTRATION",
      "TENANTASSOCIATIONREGISTRATION(INRESPONSETOOFFEROFSALE)" = "207"

      "RIGHTSOFFIRSTREFUSAL",
      "RIGHTOFFIRSTREFUSAL",
      "RIGHTOFFIRSTREFUSALNOTICES(SF,2-4&5+UNITS)",
      "RIGHTOFFIRSTREFUSALNOTICE",
      "RIGHTOFFIRSTREFUSALNOTICES" = "211"
      
      "TOPALETTEROFINTEREST",
      "LETTEROFINTERESTTOPA","LETTEROFINTEREST(TOPA)",
      "LETTEROFINTEREST" = "212"
      
      "TOPAASSIGNMENTOFRIGHTS",
      "ASSIGNMENTOFRIGHTTOPA",
      "ASSIGNEMETOFRIGHTTOPA", "ASSIGNMENTOFRIGHTS", "ASSIGNMENTOFRIGHTS(TOPA)" = "213"
      
      "TOPACOMPLAINT","TOPACOMPLAINTS", "TOPACOMPLIANT", "COMPLAINT" = "214"
      
      'SFDNOTICEOFSOLICITATIONOFOFFER&NOTICEOFINTENTTOSELL',
      'SINGLEFAMILYDWELLINGNOTICEOFSOLICITATIONOFOFFER&NOTICEOFINTENTTOSELL' = "215"
      
      "SFDLETTERTOLANDLORD","TENANTSNOTICETOLANDLORD",
      "TENANTSLETTERTOLANDLORD"= "216"
      
      "SFDCLAIMOFELDERLYORDISABLEDSTATUS",
      "TENANTSCLAIMOFELDERLY/DISABLEDSTATUS" = "217"
      
      "OFFEROFSALERESPONSE-TENANTS",
      "TENANTRESPONSETOOFFEROFSALENOTICES",
      "TENANTRESPONSETOOFFEROFSALENOTICE" = "218"
      
      "NOTICEOFTRANSFER-EXEMPTIONFROMTOPARIGHTS",
      "NOTICEOFTRANSFER-EXEMPTTRANSACTIONSFROMTOPARIGHTS" = "219"
      
      "2-4UNITSNOTICEOFTRANSFER" = "227"
      
      "5+UNITSNOTICEOFTRANSFER" = "230"
      
      "TENANTASSOCIATIONREGISTRATION(W/INTENTTOPURCHASE)",
      "TENANTASSOCIATIONREGISTRATIONANDLETTEROFINTERESTTOPURCHASE",
      "TENANTASSOCIATIONREGISTRATION(RESPONSETOOFFEROFSALE)" 
      "TENANTASSOCIATIONREGISTRATION(RESPONSETOOFFEROFSALEBYOWNER)",
      "TENANTASSOCIATIONREGISTRATION-OFS",
      "TENANTASSOCIATIONREGISTRATION(RESPONSETOOFFEROFSALE)",
      "TENANTASSOCIATIONREGISTRATION(RESPONSETOOFFEROFSALEBYOWNER)" = "235"
      
      "TENANTSTATEMENTOFINTERESTTOPURCHASE",
      "TENANTSTATEMENT",
      "STMTOFINTEREST-T/A",
      "STATEMENTOFINTEREST" = "237"
      
      "RIGHTOFFIRSTREFUSAL(SFD)",
      "SFDRIGHTOFFIRSTREFUSAL",
      "RIGHTOFFIRSTREFUSAL(SINGLEFAMILY)",
      "RIGHTOFFIRSTREFUSAL(SF)" = "241"
      
      "2-4UNITSRIGHTOFFIRSTREFUSAL",
      "RIGHTOFFIRSTREFUSAL(2-4)",
      "RIGHTOFFIRSTREFUSAL(2-4UNITS)" = "242"

      "SFDNOTICEOFTRANSFER" = "243"

      "PETITIONFORRECONSIDERATION" = "244"

      "WARRANTYSECURITYRELEASEREQUEST" = "245"
      
      "5+UNITSRIGHTOFFIRSTREFUSAL",
      "RIGHTOFFIRSTREFUSAL(5ORMORE)" = "246"

      "WARRANTYSECURITYLETTEROFCREDIT", 
      "WARRANTYSECURITY?LETTEROFCREDIT"  = "247"
      
      "NOTICEOFTRANSFERCERTIFICATIONREQUEST" = "250"
      
      "NOTICEOFINTENTTOCONVERT" = "260"
      
      "NOTICEOFINTENTTOCONVERT(OFFERTOPURCHASECONDOMINIUMUNIT)" = "261"
      
      "NOTICEOFINTENTTOCONVERT(NOTICEAFTERCONVERSION)" = "262"
      
      "CONVERSIONFEE/CORRESPONDENCE" = "265"
      
      "CONVERSIONFEEPAYMENT" = "267"
      
      "CONVERSIONFEEREDUCTIONREQUEST" = "268"
      
      "OFFEROFSALENOTICECORRESPONDENCE",
      "OFFEROFSALECORRESPONDENCE",
      "OTHEROFFEROFSALECORRESPONDENCE",
      "OFFEROFSALEMISCELLANEOUSCORRESPONDENCE" = "270"
      
      "OFFEROFSALE(MISCINFORMATION)",
      "OFFEROFSALE(MISCELLANEOUSINFORMATION)",
      "OFFEROFSALE-MISCDOCUMENTS" = "275"
      
      "CONDOMINIUMCONVERSIONSVACANCYEXEMPTIONINSPECTIONSLISTING" = "280"
      
      "VACANCY/NHAEXEMPTIONAPPLICATIONS" = "282"
      
      "CONVERSIONEXEMPTIONS(VACANT)",
      "CONVERSIONEXEMPTIONREQUEST(VACANT)" = "285"
      
      "COOPERATIVECONVERSIONEXEMPTIONAPPLICATION",
      "COOPERATIVECONVERSIONEXEMPTION" = "290"
      
      "VACANCY/COOPEXEMPTIONAPPLICATION" = "291"
      
      "EXEMPTIONREQUEST",
      "EXEMPTIONREQUESTAPPLICATION",
      "EXEMPTIONAPPLICATIONS" = "295"
      
      "MISCELLANEOUSINFORMATION" = "300"
      
      "TERMINATIONOFCONDOMINIUM" = "310"
      
      "TERMINATIONOFSALESCONTRACT" = "312"
      
      "SALESCONTRACT" = "320"
      
      "DISABILITYSURVEYFORTENANTELECTION" = "330"
      
      "INTENTTOFILEPETITION",
      "NOTICEOFINTENTTOFILEPETITION" = "335"
      
      other = " ";

  run;

%mend Rcasd_text2type_fmt;

/** End Macro Definition **/

